CREATE TABLE os_content_evaluation (
	id INT NOT NULL AUTO_INCREMENT,
	content_id INT NOT NULL,
	rate INT NOT NULL DEFAULT '0',
	comment VARCHAR(2048),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
)